name: Create Flutter Project

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.4'

      - name: Create new Flutter project
        run: flutter create -t app ShayanWalletNew

      - name: List files
        run: ls -R ShayanWalletNew
